export interface Property {
  id: string
  title: string
  price: number
  deposit: number
  address: string
  city: string
  state: string
  bedrooms: number
  bathrooms: number
  propertyType: "Studio" | "1BR" | "2BR" | "3BR+" | "House"
  description: string
  amenities: string[]
  images: string[]
  availableDate: string
  landlordId: string
  landlordName: string
  landlordPhone: string
  landlordEmail: string
  featured: boolean
}

export interface Landlord {
  id: string
  name: string
  email: string
  phone: string
  properties: string[]
  totalRevenue: number
  activeListings: number
  pendingApplications: number
}

export const sampleProperties: Property[] = [
  {
    id: "1",
    title: "Kensington High Street, Kensington, W8",
    price: 2800,
    deposit: 2800,
    address: "45 Kensington High Street, W8 5ED",
    city: "London",
    state: "Greater London",
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "2BR",
    description:
      "Stunning modern flat in the heart of Kensington with excellent transport links, period features, and contemporary kitchen with integrated appliances.",
    amenities: ["Gym", "Parking", "Pet-friendly", "Balcony", "Washing machine"],
    images: ["/modern-downtown-loft.png", "/modern-loft-kitchen.png", "/loft-bedroom-city-view.png"],
    availableDate: "2025-12-15",
    landlordId: "landlord1",
    landlordName: "James Thompson",
    landlordPhone: "020 7123 4567",
    landlordEmail: "james@aceproperties.co.uk",
    featured: true,
  },
  {
    id: "2",
    title: "Brick Lane, Shoreditch, E1",
    price: 1650,
    deposit: 1650,
    address: "78 Brick Lane, E1 6RL",
    city: "London",
    state: "Greater London",
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "Studio",
    description:
      "Charming studio flat perfect for young professionals in trendy Shoreditch. Features high ceilings, large sash windows, and modern kitchenette.",
    amenities: ["Gym", "Roof terrace", "Concierge service"],
    images: ["/cozy-studio-apartment.png", "/studio-kitchenette.png", "/studio-bathroom.png"],
    availableDate: "2024-12-15",
    landlordId: "landlord2",
    landlordName: "Emma Williams",
    landlordPhone: "020 7234 5678",
    landlordEmail: "emma@aceproperties.co.uk",
    featured: true,
  },
  {
    id: "3",
    title: "Maple Grove, Didsbury, M20",
    price: 3500,
    deposit: 3500,
    address: "12 Maple Grove, M20 2RN",
    city: "Manchester",
    state: "Greater Manchester",
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "House",
    description:
      "Beautiful Victorian family home with large rear garden, period features, and modern kitchen extension. Located in a quiet residential area with excellent schools nearby.",
    amenities: ["Parking", "Pet-friendly", "Garden", "Garage", "Dishwasher"],
    images: ["/spacious-family-home.png", "/cozy-family-living-room.png", "/family-home-kitchen.png"],
    availableDate: "2025-08-15",
    landlordId: "landlord1",
    landlordName: "James Thompson",
    landlordPhone: "020 7123 4567",
    landlordEmail: "james@aceproperties.co.uk",
    featured: true,
  },
  {
    id: "4",
    title: "Canada Square, Canary Wharf, E14",
    price: 4200,
    deposit: 4200,
    address: "25 Canada Square, E14 5LQ",
    city: "London",
    state: "Greater London",
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "3BR+",
    description:
      "Exceptional high-rise apartment with panoramic Thames and city views. Features floor-to-ceiling windows, premium finishes, and access to exclusive building facilities.",
    amenities: ["Gym", "Swimming pool", "Concierge", "Parking", "Balcony"],
    images: ["/luxury-high-rise-living-room.png", "/luxury-apartment-bedroom.png", "/high-rise-balcony-view.png"],
    availableDate: "2025-10-01",
    landlordId: "landlord3",
    landlordName: "Oliver Davies",
    landlordPhone: "020 7345 6789",
    landlordEmail: "oliver@aceproperties.co.uk",
    featured: false,
  },
  {
    id: "5",
    title: "High Street, Chipping Campden, GL54",
    price: 1850,
    deposit: 1850,
    address: "Rose Cottage, High Street, GL54 1AB",
    city: "Chipping Campden",
    state: "Gloucestershire",
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "1BR",
    description:
      "Delightful honey-stone cottage in the heart of the Cotswolds with private garden. Features original beams, inglenook fireplace, and modern amenities.",
    amenities: ["Pet-friendly", "Garden", "Parking", "Washing machine"],
    images: ["/charming-cottage-apartment.png", "/cozy-cottage-bedroom.png", "/cottage-garden.png"],
    availableDate: "2024-09-20",
    landlordId: "landlord2",
    landlordName: "Emma Williams",
    landlordPhone: "020 7234 5678",
    landlordEmail: "emma@aceproperties.co.uk",
    featured: false,
  },
  {
    id: "6",
    title: "Broad Street, Birmingham City Centre, B1",
    price: 1950,
    deposit: 1950,
    address: "88 Broad Street, B1 2HP",
    city: "Birmingham",
    state: "West Midlands",
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "2BR",
    description:
      "Contemporary city centre flat with open-plan living, integrated appliances, and washer/dryer. Walking distance to New Street Station and shopping districts.",
    amenities: ["Gym", "Parking", "Washing machine", "Balcony", "Storage"],
    images: ["/modern-condo-living-room.png", "/modern-condo-kitchen.png", "/cozy-condo-bedroom.png"],
    availableDate: "2024-10-15",
    landlordId: "landlord3",
    landlordName: "Oliver Davies",
    landlordPhone: "020 7345 6789",
    landlordEmail: "oliver@aceproperties.co.uk",
    featured: true,
  },
]

export const kentProperties: Property[] = [
  {
    id: "kent1",
    title: "High Street, Canterbury, CT1",
    price: 1200,
    deposit: 1200,
    address: "23 High Street, CT1 2RX",
    city: "Canterbury",
    state: "Kent",
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "1BR",
    description:
      "Charming period apartment in historic Canterbury city centre with original features and modern amenities. Walking distance to cathedral and university.",
    amenities: ["Pet-friendly", "Washing machine", "City centre location"],
    images: ["/charming-cottage-apartment.png", "/cozy-cottage-bedroom.png", "/cottage-garden.png"],
    availableDate: "2025-09-15",
    landlordId: "landlord1",
    landlordName: "James Thompson",
    landlordPhone: "020 7123 4567",
    landlordEmail: "james@aceproperties.co.uk",
    featured: true,
  },
  {
    id: "kent2",
    title: "Marine Parade, Margate, CT9",
    price: 950,
    deposit: 950,
    address: "15 Marine Parade, CT9 1DH",
    city: "Margate",
    state: "Kent",
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "Studio",
    description:
      "Coastal studio apartment with sea views and direct beach access. Perfect for young professionals seeking seaside living with good transport links to London.",
    amenities: ["Sea view", "Balcony", "Beach access"],
    images: ["/cozy-studio-apartment.png", "/studio-kitchenette.png", "/studio-bathroom.png"],
    availableDate: "2025-09-05",
    landlordId: "landlord2",
    landlordName: "Emma Williams",
    landlordPhone: "020 7234 5678",
    landlordEmail: "emma@aceproperties.co.uk",
    featured: true,
  },
  {
    id: "kent3",
    title: "Castle Street, Tonbridge, TN9",
    price: 1650,
    deposit: 1650,
    address: "8 Castle Street, TN9 1BH",
    city: "Tonbridge",
    state: "Kent",
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "2BR",
    description:
      "Modern apartment in historic Tonbridge with castle views. Features contemporary kitchen, parking space, and excellent rail connections to London.",
    amenities: ["Parking", "Castle views", "Modern kitchen", "Rail connections"],
    images: ["/modern-condo-living-room.png", "/modern-condo-kitchen.png", "/cozy-condo-bedroom.png"],
    availableDate: "2025-10-01",
    landlordId: "landlord3",
    landlordName: "Oliver Davies",
    landlordPhone: "020 7345 6789",
    landlordEmail: "oliver@aceproperties.co.uk",
    featured: true,
  },
  {
    id: "kent4",
    title: "The Green, Sevenoaks, TN13",
    price: 2200,
    deposit: 2200,
    address: "12 The Green, TN13 1JG",
    city: "Sevenoaks",
    state: "Kent",
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "3BR+",
    description:
      "Elegant Georgian townhouse overlooking Sevenoaks Green with period features and modern conveniences. Perfect for families with excellent schools nearby.",
    amenities: ["Garden", "Parking", "Period features", "Family-friendly"],
    images: ["/spacious-family-home.png", "/cozy-family-living-room.png", "/family-home-kitchen.png"],
    availableDate: "2025-09-20",
    landlordId: "landlord1",
    landlordName: "James Thompson",
    landlordPhone: "020 7123 4567",
    landlordEmail: "james@aceproperties.co.uk",
    featured: true,
  },
]

export const midlandsProperties: Property[] = [
  {
    id: "midlands1",
    title: "New Street, Birmingham, B2",
    price: 1400,
    deposit: 1400,
    address: "56 New Street, B2 4DU",
    city: "Birmingham",
    state: "West Midlands",
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "1BR",
    description:
      "Modern city centre apartment with excellent transport links and shopping on your doorstep. Perfect for professionals working in Birmingham's business district.",
    amenities: ["City centre", "Transport links", "Shopping nearby", "Modern fixtures"],
    images: ["/modern-downtown-loft.png", "/modern-loft-kitchen.png", "/loft-bedroom-city-view.png"],
    availableDate: "2025-09-10",
    landlordId: "landlord1",
    landlordName: "James Thompson",
    landlordPhone: "020 7123 4567",
    landlordEmail: "james@aceproperties.co.uk",
    featured: true,
  },
  {
    id: "midlands2",
    title: "Castle Street, Nottingham, NG1",
    price: 1100,
    deposit: 1100,
    address: "28 Castle Street, NG1 6AF",
    city: "Nottingham",
    state: "Nottinghamshire",
    bedrooms: 0,
    bathrooms: 1,
    propertyType: "Studio",
    description:
      "Stylish studio apartment in Nottingham's historic city centre. Walking distance to universities, shops, and nightlife with excellent value for money.",
    amenities: ["Historic location", "University nearby", "City centre", "Great value"],
    images: ["/cozy-studio-apartment.png", "/studio-kitchenette.png", "/studio-bathroom.png"],
    availableDate: "2025-09-25",
    landlordId: "landlord2",
    landlordName: "Emma Williams",
    landlordPhone: "020 7234 5678",
    landlordEmail: "emma@aceproperties.co.uk",
    featured: true,
  },
  {
    id: "midlands3",
    title: "High Street, Leicester, LE1",
    price: 1300,
    deposit: 1300,
    address: "42 High Street, LE1 5YR",
    city: "Leicester",
    state: "Leicestershire",
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "2BR",
    description:
      "Spacious two-bedroom flat in Leicester city centre with modern amenities and good transport connections. Ideal for sharers or small families.",
    amenities: ["Spacious", "Modern amenities", "Transport links", "City centre"],
    images: ["/modern-condo-living-room.png", "/modern-condo-kitchen.png", "/cozy-condo-bedroom.png"],
    availableDate: "2025-10-15",
    landlordId: "landlord3",
    landlordName: "Oliver Davies",
    landlordPhone: "020 7345 6789",
    landlordEmail: "oliver@aceproperties.co.uk",
    featured: true,
  },
  {
    id: "midlands4",
    title: "Victoria Road, Coventry, CV1",
    price: 1600,
    deposit: 1600,
    address: "15 Victoria Road, CV1 3JX",
    city: "Coventry",
    state: "West Midlands",
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "3BR+",
    description:
      "Family-friendly house near Coventry University with garden space and parking. Perfect for students or young families seeking affordable city living.",
    amenities: ["Garden", "Parking", "University nearby", "Family-friendly"],
    images: ["/spacious-family-home.png", "/cozy-family-living-room.png", "/family-home-kitchen.png"],
    availableDate: "2025-09-30",
    landlordId: "landlord1",
    landlordName: "James Thompson",
    landlordPhone: "020 7123 4567",
    landlordEmail: "james@aceproperties.co.uk",
    featured: true,
  },
]

export const sampleLandlords: Landlord[] = [
  {
    id: "landlord1",
    name: "James Thompson",
    email: "james@aceproperties.co.uk",
    phone: "020 7123 4567",
    properties: ["1", "3"],
    totalRevenue: 6300,
    activeListings: 2,
    pendingApplications: 5,
  },
  {
    id: "landlord2",
    name: "Emma Williams",
    email: "emma@aceproperties.co.uk",
    phone: "020 7234 5678",
    properties: ["2", "5"],
    totalRevenue: 3500,
    activeListings: 2,
    pendingApplications: 3,
  },
  {
    id: "landlord3",
    name: "Oliver Davies",
    email: "oliver@aceproperties.co.uk",
    phone: "020 7345 6789",
    properties: ["4", "6"],
    totalRevenue: 6150,
    activeListings: 2,
    pendingApplications: 7,
  },
]
